# Generated by Django 4.2.18 on 2025-01-20 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Tk', 'Танки'), ('Hl', 'Хиллы'), ('DD', 'ДД'), ('Mr', 'Торговцы'), ('Gm', 'Гилдмастера'), ('Kg', 'Квестгиверы'), ('Bm', 'Кузнецы'), ('Tn', 'Кожевники'), ('Pm', 'Зельевары'), ('Sm', 'Мастера заклинаний')], default='Tk', max_length=2)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Build_Board.customer')),
            ],
        ),
    ]
